server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/institute
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
